.config:
  cache:
    key: aquila-config
    paths:
      - aquila-config/.gradle
  only:
    changes:
      - aquila-config

configBuild:
  stage: lib-build
  script:
    - cd aquila-config
    - gradle publishToMavenLocal
  extends:
    - .config
  artifacts:
    paths:
      - aquila-config/build
    expire_in: 1 week

configTest:
  stage: lib-test
  script:
    - cd aquila-config
    - gradle test
  extends:
    - .config

configPublish:
  stage: lib-deploy
  script:
    - cd aquila-config
    - gradle publish
  extends:
    - .config
    - .deployment
  artifacts:
    paths:
      - aquila-config/build/libs/*.jar
    expire_in: 1 month