.config:
  before_script:
    - cd aquila-config
    - chmod +x gradlew
  cache:
    key: aquila-config
    paths:
      - aquila-config/.gradle
  except:
    changes:
      - aquila-app/*/version.properties

configBuild:
  stage: lib-build
  script:
    - ./gradlew publishToMavenLocal
  extends:
    - .config
  artifacts:
    paths:
      - aquila-config/build
    expire_in: 1 week

configTest:
  stage: lib-test
  script:
    - ./gradlew test
  extends:
    - .config

configPublish:
  stage: lib-deploy
  script:
    - ./gradlew publish
  extends:
    - .config
    - .deployment
  artifacts:
    paths:
      - aquila-config/build/libs/*.jar
    expire_in: 1 month